version: '2.1'
services:

  #
  # fake sipp carrier
  #
  rabbitmq:
    image: 'bitnami/rabbitmq:3.7'
    ports:
    - "5672:5672"
    - "15672:15672"
    environment:
    - RABBITMQ_PASSWORD=password
